name: Build test image and run tests

on:
  push:

jobs:
  run_e2e_tests:
    name: 'Run e2e tests'
    runs-on: ubuntu-20.04
    timeout-minutes: 60
    env:
      DEX_IMAGE_TAG: $GIT_BRANCH_NAME
      DEX_FEE_RECIPIENT: ${{ secrets.APP_FEE_RECIPIENT }}
      DEX_ALCHEMY_API_KOVAN_KEY: ${{ secrets.APP_ALCHEMY_KOVAN_KEY }}
      EXCHANGE_ALCHEMY_API_KOVAN_KEY: ${{ secrets.APP_ALCHEMY_KOVAN_KEY }}
      CYPRESS_TEST_TAG: $GIT_BRANCH_NAME
      CYPRESS_GROUP: '${{ github.ref_name }}-${{github.run_attempt}}'
      CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
    steps:
      - name: Get branch name
        id: git-branch-name
        uses: EthanSK/git-branch-name-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Checkout injective-devops
        uses: actions/checkout@master
        with:
          repository: InjectiveLabs/injective-devops
          ref: 'f/standalone_env'
          token: ${{ secrets.BARTEKS_PAT }}
          path: ./injective-devops
      - name: Start standalone network
        run: cd injective-devops && make start-dex
